version: '3'

services:
  server:
    container_name: NODEJS_SRV_TRANSP_BR
    build: '.'
    volumes:
      - .:/node-app
      - ./node_modules:/node-app/node_modules
    environment:
      env_file: .env
    depends_on:
      - db
    links:
      - db
    ports:
      - '9000:9000'

  db:
    image: "mariadb:${MARIADB_VERSION}"
    restart: 'always'
    expose:
      - '3306'
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '3306:3306'
    volumes: 
      - ./data:/data
      - ./logs:/log/db      
    environment:
      DB_HOSTNAME: db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}